//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCS2012
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public TblProduct()
        {
            this.TblTransactionItems = new HashSet<TblTransactionItem>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
    
        public virtual TblProductType TblProductType { get; set; }
        public virtual ICollection<TblTransactionItem> TblTransactionItems { get; set; }
    }
}
