//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCS2012
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransaction
    {
        public TblTransaction()
        {
            this.TblTransactionItems = new HashSet<TblTransactionItem>();
        }
    
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual ICollection<TblTransactionItem> TblTransactionItems { get; set; }
    }
}
